feat(iftools_287): add IsNonEmptyString
honestica/typeguard pull request #20
Opened 2023-05-30 10:06 UTC by henricazottes

We often have the case of `value: string | undefined` and it's a bit tedious to both check for definition and non emptiness: 
``` typescript
if(TypeGuard.IsDefined(value) && value !== '') {}
// or for the orther way around
if(!TypeGuard.IsDefined(value) || value === '') {}
```
I propose to add a new typeguard for this common case inspired by the existing `TypeGuard.IsPopulatedArray` : 
``` typescript
if(TypeGuard.IsPopulatedString(value)) {}
```

It's just syntax sugar

2023-05-30 10:07 UTC, henricazottes commented
I've thought about naming the method `IsNonEmptyString` but it doesn't combine well with it negation form `!IsNonEmptyString()` because of the double negation

2023-05-30 12:46 UTC, blephy requested changes

2023-05-30 12:46 UTC, blephy commented on tsconfig.json
> -		"charset": "UTF-8",
Dû au passage à une version de typescript plus récente ?

Il n'y a pourtant pas d'update de dépendance ici, je préfère autant séparer ce changement dans une autre PR

2023-05-30 12:46 UTC, blephy commented on README.md
> +
Personnellement j'aurais vu un peu plus loin directement, en partant de la meme implémentation que `IsArray`.

1. modifier `IsString` pour prendre un deuxième argument, sous forme d'objet, avec une option `minLength`
2. utiliser `IsString` dans `IsPopulatedString` avec un `minLength` à `1`

Ca donnerait l'avantage de pouvoir s'assurer qu'une string à au minimum une longueur de 2 par exemple. Et ca suit l'implémentation et la logique déjà présente.

2023-05-30 12:51 UTC, henricazottes commented on tsconfig.json
> -		"charset": "UTF-8",
Oui j'ai pas compris pourquoi le linter était pas content. J'avais changé dans le doute mais je vais revert 👍

2023-05-30 12:52 UTC, henricazottes commented on .vscode/settings.json
> +	"editor.renderFinalNewline": "on",
Euh, je sais pas d'où ça sort 👀

2023-05-30 12:53 UTC, henricazottes commented on README.md
> +
Yep j'y ai aussi pensé, mais vu que j'en avais pas l'usage je voulais pas perdre trop de temps du coup j'ai pas fait. PR welcome ceci dit :)

2023-05-30 12:55 UTC, valentin-lifen commented on src/TypeGuard.ts
> +	public static IsPopulatedString(
mineur mais j'aurais eu tendance a faire la méthode inverse `IsEmptyString`

2023-05-30 12:56 UTC, blephy commented on README.md
> +
C'est une lib très bas niveau, c'est important de voir sur le long terme les directions prises en terme d'API pour ne pas à devoir faire des modifications d'implémentations / utilisations dans les composants qui l'utilise.

Meme si tu n'en a pas besoin maintenant, ca ne coûterais pas grand chose de l'implémenter comme tel aujourd'hui, non ?

2023-05-30 12:57 UTC, blephy commented on .vscode/settings.json
> +	"editor.renderFinalNewline": "on",
Yes c'est que l'API de VSCode à changer.

A la limite on peut faire passer ce changement dans une autre PR avec l'update des dépendances sans release / publish

2023-05-30 13:02 UTC, valentin-lifen commented on src/TypeGuard.ts
> +	): value is string
par contre je ne suis pas sûr que ca aide vraiment en fait, car la tu dis que value est de type `string` mais pour typescript ca peut encore valoir `""` si je ne me trompe pas ... et je ne sais pas trop comment on pourrait dire que c'est une string d'une taille au moins 1

2023-05-30 13:30 UTC, blephy commented on src/TypeGuard.ts
> +	): value is string
> et je ne sais pas trop comment on pourrait dire que c'est une string d'une taille au moins 1

`value is ` ${string}``

2023-05-30 13:31 UTC, blephy commented on src/TypeGuard.ts
> +	): value is string
Dans tous les cas, je pense pas qu'il faille allez jusqu'au typage de ce genre de check.

2023-05-30 13:47 UTC, pauldub commented on src/TypeGuard.ts
> +	): value is string
IMO on ne veut pas, le langage s'y prête pas trop.

Pour la science, c'est implémenté ici à l'aide d'un newtype: https://github.com/gcanti/newtype-ts et ici avec le système de typage: https://stackoverflow.com/a/63933117

Mais dans notre cas c'est overkill.

2023-05-30 13:47 UTC, henricazottes commented on src/TypeGuard.ts
> +	): value is string
Short answer, on peut pas :')
J'ai regardé vite fait et ça demande des petits hacks. Mais c'est assez limité, ça apporte pas vraiment d'avantages de typage. Tu peux voir quelques tests ici basé sur ce que j'ai pu voir comme options: [TS Playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwgFgQwE4IMbAkqBeKByAQjwB88AiEvAYkoBJKBSSgMkoB09KAKSgSkoBUlANSUANJQC0lAHSUA9JQAMlAIyUATJQDMlACyUArJQBslAOyUAHJQCclAFyUA3JQA8lbJQB8lAPyUAAKUAIKUAEKUMJQAIpQAopQAYpQA4pQAEpQAkpQAUpQA0pQAMpQAspQAcpQA8pQACpQAipQASpQAypQAKpQAqpQAapQA6pQAGpQAmpQAWpQA2uycpAC6lAB6lAD6lAAGlAiUAEaUqJQAJpQQlABmlADmlHCUAJaUAFaUANaUADaUAC2lAAdpQAPaUMCUACOlCQlAAzpRgJQAK6UABulAA7pQAB6UECUABelAA3pRSKQAL6UAB+lAAhZQAEWUADFlAAJZQAKWUABllAA5ZQABWUACVlAAVZQANWUAA1lAAdZQAPWUAANlAAjZQAE2UADNlAALZQAK2UABtlAA7ZQAB2UACdlAAXZQAN2UAA9lAAvZQAH2UAD9lAAA5QAIOUABDlAAw5QACOUACjlAAY5QAOOUAATlAAk5QAFOUADTlAAM5QALOUABzlAA85QAAuUACLlAAS5QAMuUAArlAAq5QAGuUADrlAAG5QAJuUABblAA25QADuUAC7lAAe5QAPuUAAHlAAh5QAEeUADHlAAJ5QAKeUABnlAAOeUAAF5QACXlAAFeUAA15QAA3lAALeUAAd5QAD3lAAA+UAAj5QABPlAAM+UAAL5QACvlAAG+UAA75QAAflAAJ+UAAX5QADflAAD+UAAv5QAB-lAAP94M4ABQqAQqCSLALAGQhG0IQwD08RtJ0DhQCESAoCAbgqUgbygo83g4FAyxEBIFASDQEj0BITASKwEgcHgEg8BI-ASEIEiiBIYV4NIEhyBIigSCoEjqBIWgSLoEgGBIxgSGYEiWBINgSPYEhOBIrgSB4EheBIvgSAEEjBBIYQSJEEjRBIcQSIkEgpBI6QSFkEi5BIBQSMUEhlBIlQSDUEj1BITQSK0EgdBI3QSH0EiDBIIwSOMEhTBIswSAsEjLN5nASBsEjbBIewSIcEjHBIZwSBcEjXBItwSA8EjPBIrwSB8EjfBIfwSICEgghI4ISFCEgwhI8ISIiEgohIaISJiEg4hI+ISESEgkhI5ISFSEikBI9ISEyEishIHISNyEh8hIgoSCKEjihIUoSLKEgKhIyoSGqEiahIOoSPqEhGhIpoSBaEjWhIdoSI6EguhI7oSF6Ei+hIAYSMGEhhhIkYSDGEjxhISYSKmEgZhI2YSHmEiFhIJYSOWEhVhItYSA2EjNhIbYSJ2Eg9hI-YSEOEijhIE4SNOEhzhIi4SCuEjrhIW4SLuEgHhIx4SGeEiXhIN4SPeEhPhIr4SB+EjfhIf4SIBEggRI4ESFBEiwRICESMhEhoRImESDhEj4RIRESKREgURI1ESHREiMRILESOxEhcRIvESAJEjCRIYkSJJEgyWsUBIggwBvEidxvBASKGcZCCmfAyBoBgSDePJoCQFADQIRgHRP8a+EBLidGABZKytl9i0ApO-FA6BMC0ngeZSyjxaT7HknJO46JQToDeEpKAt9IHQMeFwLECB-joggAZfBPxQQQlxKCXgBkqE0OgLfS+UCMFQApEgCAwB0RIFBFAP+EAIR3CgBw2hOBsC4DwOgqysk5K0jkrg-BhDiG30AcA0BGAIG8KspQ6htD6GgkYcw1h7CzFcKfnokBYCjHkP4XJKAUBBHCNESQpEZCMGmM4bwKAzBmBqQ0lpHSekZCWVQDQy4j9Am0N4PJdRmiCE3x0UieIQIwCgH8SY2RdCoAMKYSwthMi7G+J4a4ik7jPFCJEWI0hxiKFFOCaEypnD5GKNUWkxSylVLAAhMMgyyjHhQGICU0ECT76gnAbZTgOC3h3C4AQW+OS8kgAKRQ4ZwzeDBLqR4gZSIIT-AgDIf4EJdkjIhCkqA8h5DiNudU-BszLLgLURolZXBdFAKcYYnZXA9l3MOfUn5ILLkQCssAOAPSoBKDBR445SlTnnMudcrgZBOhwAhCAy4UB5lYkwFARAYBICgjIPcx5UAejgEfqgCyeSoCXAhI-cEqkkQQC4apBAT98GCLQIgE45yoCKQSfU9RtIgA)

2023-05-30 13:51 UTC, henricazottes commented on src/TypeGuard.ts
> +	public static IsPopulatedString(
On peut l'ajouter. Mais l'usage diffère un peu. J'ai ajouté l'util car je suis tombé sur beaucoup de check de string non empty. Problème avec cependant avec `IsEmptyString` c'est que ça filtre pas les undefined. Exemple :
``` typescript
function isEmptyString(value: unknown): value is string {
  return isString(value) && value === '';
}

const toto: string | undefined = undefined;

if(!IsEmptyString) {
    doStuff(toto); // toto is undefined
}

if(isString(toto) && !isEmptyString) { // ça bloque bien mais on revient au problème initial d'avoir un double check à faire
    doStuff(toto);
}
```

À la limite, faudrait `IsEmptyStringOrUndefied`. Mais bon, ça fait un peu frankenstein imo

2023-05-30 16:09 UTC, valentin-lifen commented on src/TypeGuard.ts
> +		return TypeGuard.IsString(value) && value !== "";
Idem ici, on pourrait utiliser `TypeGuard.IsString(value, {minLength:1})`

2023-05-31 08:04 UTC, valentin-lifen commented on src/TypeAssertion.ts
> +			 */
mineur pourquoi ce comment vide ?

2023-05-31 08:05 UTC, valentin-lifen approved these changes

2023-05-31 09:11 UTC, blephy approved these changes
LGTM

2023-05-31 09:12 UTC, blephy commented
J'espère par contre que le publish va fonctionner, j'ai comme l'impression que le token semantic-release a expiré. On verra au merge.

2023-05-31 09:18 UTC, blephy requested changes
Encore un dernier petit effort en fait. Je viens de check les tests de mutation, tu as introduit un mutant non killed

Il faut que tu check aussi la string qui est throw avec le maxLength

<img width="1147" alt="Capture d’écran 2023-05-31 à 11 16 50" src="https://github.com/honestica/typeguard/assets/24233935/9eabc399-74ad-4a63-886f-975f2701c514">

2023-05-31 15:42 UTC, blephy approved these changes

2023-05-31 15:43 UTC, merged

2023-05-31 16:12 UTC, blephy commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ts-predicate/v/1.1.0)
- [GitHub release](https://github.com/honestica/typeguard/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: